// Date: 5/12/2014 6:20:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package dmf444.ExtraFood.Client.renderer;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOven extends ModelBase
{
  //fields
    ModelRenderer Shape2a;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape5a;
    ModelRenderer Shape6;
    ModelRenderer Shape6b;
    ModelRenderer Shape6a;
    ModelRenderer Shape1;
    ModelRenderer Shape1a;
    ModelRenderer Shape1b;
    ModelRenderer Shape7;
  
  public ModelOven()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape2a = new ModelRenderer(this, 60, 0);
      Shape2a.addBox(0F, 0F, 0F, 2, 10, 2);
      Shape2a.setRotationPoint(6F, 14F, 6F);
      Shape2a.setTextureSize(128, 64);
      Shape2a.mirror = true;
      setRotation(Shape2a, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 60, 0);
      Shape2.addBox(0F, 0F, 0F, 2, 10, 2);
      Shape2.setRotationPoint(-8F, 14F, 6F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 60, 12);
      Shape3.addBox(0F, 0F, 0F, 16, 2, 16);
      Shape3.setRotationPoint(-8F, 12F, -8F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 68, 0);
      Shape4.addBox(0F, 0F, 0F, 16, 4, 1);
      Shape4.setRotationPoint(-8F, 8F, 5F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 29);
      Shape5.addBox(0F, 0F, 0F, 2, 2, 1);
      Shape5.setRotationPoint(4F, 9F, 6F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape5a = new ModelRenderer(this, 0, 29);
      Shape5a.addBox(0F, 0F, 0F, 2, 2, 1);
      Shape5a.setRotationPoint(-6F, 9F, 6F);
      Shape5a.setTextureSize(128, 64);
      Shape5a.mirror = true;
      setRotation(Shape5a, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 60);
      Shape6.addBox(0F, 0F, 0F, 16, 3, 1);
      Shape6.setRotationPoint(-8F, 9F, 4F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape6b = new ModelRenderer(this, 75, 62);
      Shape6b.addBox(0F, 0F, 0F, 16, 1, 1);
      Shape6b.setRotationPoint(-8F, 11F, 2F);
      Shape6b.setTextureSize(128, 64);
      Shape6b.mirror = true;
      setRotation(Shape6b, 0F, 0F, 0F);
      Shape6a = new ModelRenderer(this, 36, 61);
      Shape6a.addBox(0F, 0F, 0F, 16, 2, 1);
      Shape6a.setRotationPoint(-8F, 10F, 3F);
      Shape6a.setTextureSize(128, 64);
      Shape6a.mirror = true;
      setRotation(Shape6a, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 26, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 10, 14);
      Shape1.setRotationPoint(7F, 14F, -8F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1a = new ModelRenderer(this, 26, 0);
      Shape1a.addBox(0F, 0F, 0F, 1, 10, 14);
      Shape1a.setRotationPoint(-8F, 14F, -8F);
      Shape1a.setTextureSize(128, 64);
      Shape1a.mirror = true;
      setRotation(Shape1a, 0F, 0F, 0F);
      Shape1b = new ModelRenderer(this, 72, 38);
      Shape1b.addBox(0F, 0F, 0F, 16, 11, 1);
      Shape1b.setRotationPoint(-8F, 12F, -8F);
      Shape1b.setTextureSize(128, 64);
      Shape1b.mirror = true;
      setRotation(Shape1b, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 34);
      Shape7.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape7.setRotationPoint(-8F, 23F, -8F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape2a.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape5a.render(f5);
    Shape6.render(f5);
    Shape6b.render(f5);
    Shape6a.render(f5);
    Shape1.render(f5);
    Shape1a.render(f5);
    Shape1b.render(f5);
    Shape7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
